workspace := "/srv/android-automotive"
release := "imx-automotive-16.0.0_1.1.0"
images_dir := workspace + "/releases/" + release

default:
  @just --list

build: build-container build-images

publish: publish-artifacts

init-workspace:
  sudo mkdir -p {{workspace}}
  sudo chgrp -R android-build {{workspace}}
  sudo chmod -R 2775 {{workspace}}

install-repo:
  sudo curl https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
  sudo chmod +x /usr/local/bin/repo

extract-bsp archive=(release + ".tar.gz"):
  cd {{workspace}} && tar -xzvf {{archive}}

build-container:
  cd {{workspace}}/{{release}}/device/nxp/common/dockerbuild && docker build --no-cache \
    --build-arg userid=$(id -u) \
    --build-arg groupid=$(id -g) \
    --build-arg username=$(id -un) \
    -t android-build .

build-images:
  docker run --privileged -it -v {{workspace}}/{{release}}:/work/android_src android-build /bin/bash -lc '\
    cd /work/android_src && \
    source build/envsetup.sh && \
    lunch mek_8q_car2-nxp_stable-userdebug && \
    ./imx-make.sh -j3 2>&1 | tee build-log.txt'

publish-artifacts:
  mkdir -p {{images_dir}}
  cp -r {{workspace}}/{{release}}/out/target/product/mek_8q {{images_dir}}/
  cp {{workspace}}/{{release}}/build-log.txt {{images_dir}}/ 2>/dev/null || true
