workspace := "/srv/android-automotive"
release := "imx-automotive-16.0.0_1.1.0"
source_tree := workspace + "/" + release + "/android_build"
images_dir := workspace + "/releases/" + release
build_container := "android-automotive-build"

default:
  @just --list

install-repo:
  sudo curl https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
  sudo chmod +x /usr/local/bin/repo

extract-bsp archive=(release + ".tar.gz"):
  cd {{workspace}} && tar -xzvf {{archive}}

build-container:
  cd {{source_tree}}/device/nxp/common/dockerbuild && docker build --no-cache \
    --build-arg userid=$(id -u) \
    --build-arg groupid=$(id -g) \
    --build-arg username=$(id -un) \
    -t android-build .

build:
  # Remove previous build container
  docker rm -f {{build_container}} 2>/dev/null || true
  # Run new build container in the background
  docker run -d --name {{build_container}} --entrypoint /bin/bash --privileged -v {{source_tree}}:/work/android_src android-build -lc '\
    cd /work/android_src && \
    source build/envsetup.sh && \
    lunch mek_8q_car2-nxp_stable-userdebug && \
    ./imx-make.sh -j3 2>&1'

build-status:
  docker ps -a --filter "name={{build_container}}" || true

build-logs:
  docker logs {{build_container}}

publish-artifacts:
  mkdir -p {{images_dir}}
  cp -r {{source_tree}}/out/target/product/mek_8q {{images_dir}}/

verify-artifacts:
  ls -al {{images_dir}}
  ls -al {{images_dir}}/mek_8q
